# -*- coding: utf-8 -*-
"""VSJupyterNotebook.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LEa-uxLOGG0CM7gzko0h0WiokAPvw0O4
"""

print("Hello World")
print("NED University")
print("Pakistan Zindabad")